### ISSUE TITLE
Wrong export "SheetSplitter"

### ISSUE THREAD

**Issue by rtalon83** [odrick/free-tex-packer#13]
### Current Behaviour
If you have a atlas.json when the "components" are like 

*name.subname.morename.png* ( several dots )
*name* (without extension)

The images in zip are incorrect

### Expected Behaviour

Get the name without split ('.')

1. If it has extension then nothing
2. If it hasn't extension ( add random extension? add jpeg always? I don't know )

**Comment by odrick** [comment]
Thanks, my mistake... Please, check fix here: http://free-tex-packer.com/test/

**Comment by rtalon83** [comment]
Yes! all correct!

Later, this tool might be completed by:

- Zoom +/-
- Color background
- Export PNG/JPG
- etc

If I get the time, I help you filling the splitter.

Thanks!!

**Comment by odrick** [comment]
Cool! 👍
