### ISSUE TITLE
Issue with Split Sheet in Firefox

### ISSUE THREAD

**Issue by rtalon83** [odrick/free-tex-packer#15]
### Current Behavior
Using SplitSheel tool the option open texture not work in FireFox.
In Chrome works correctly.

### Desired Behaviour
Open window to select file.

#### - Windows 7

**Comment by odrick** [comment]
Fixed. Check here: http://free-tex-packer.com/app/

**Comment by rtalon83** [comment]
Run perfectly! thanks.
