### ISSUE TITLE
Proposal pivot tool and move components

### ISSUE THREAD

**Issue by rtalon83** [odrick/free-tex-packer#17]
Hello @odrick 

I was thinking in new features for your app:

1. One section about set pivot in each image
2. Group buttons: 'SplitSheet' 'Animations' 'Pivot' at the bottom, maybe?
3. Enlarge SplitSheet

Are you developing something? Can I help you? In this moment (1-2 weeks) I have free time.

**Comment by odrick** [comment]
Great ideas! Right now I'm not planning new works on this project. You can implement these features.

**Comment by rtalon83** [comment]
Perfect!

**Comment by MistahMojo** [comment]
Hey, are pivot points still being worked upon? This software is great and it's the only big thing yet to be added.

**Comment by odrick** [comment]
I plan to do this. But I do not know when.

**Comment by rtalon83** [comment]
Hi!

I'm making the pivot function but I'm having trouble because I dont know how do it without change critical code.
The only solution I see would be a simple panel (like a Animation panel) where the user only can select only one image.
What do you think?

**Comment by odrick** [comment]
This is a very complex task. We need:

- ui for multiple images pivot editing 
- transfer pivot information to exporters
- implement pivots in exporters templates
- store pivot information in project file
- implement pivots in ftp core (as addition parameter? I'm not sure...)

I think that single window for one image not enough...

**Comment by rtalon83** [comment]
I was doing a test using a simple ui where you can see all images (simple order) but I saw a problem when you have a lot of large images (chrome memory increased 2 GB). Maybe the problem is to use Canvas rendering instead of WebGl, I don't know perfectly.
I think that the most important is making a correct UI.

**Comment by eduke2k** [comment]
Great to see that this feature is being worked on. Came here because that's the last thing I would need as well. Also, I think a single window/screen per selected sprite would be enough. The Unity editor, for example, can only edit one sprite at a time, was far as I remeber.

**Comment by wtfiwinomgs** [comment]
yea +1 from me as well need pivot point.  is there any update since jan of this year on this feature?

**Comment by wtfiwinomgs** [comment]
also if I may add, for animation with lots of frames, have a way to import pivot points from a list of x, y via .txt or something.

**Comment by JannikGM** [comment]
Can someone explain, possibly with images, what this issue is about? I don't quite understand what workflow or part of the software would benefit from having a pivot point. Are we talking about custom rotations? Is this for manual placement?

**Comment by 123survesh** [comment]
Hi @JannikGM , so a pivot point is going to define a point in an image based on which its going to be positioned on screen.
![111947-pivott](https://user-images.githubusercontent.com/8644987/100693597-3d90e280-33b3-11eb-9171-a368bad66ee9.jpg)

The above image illustrates a simple use case. So now to position the stickman based on the default pivot point, we have to factor in the space between the pivot point and the stickman, when we are writing code to position it. 

If we say position the stickman to position (100, 100) in a 2D plane, then the image will be positioned such that the pivot point is in (100, 100). But we would want our stickman's body to be on (100, 100) and using the default pivot will create an undesired offset. So to get out stickman's body on (100, 100), we may have to manually set the image's pivot in code (if supported), or change the position from (100, 100) to say (110, 120).

But if we had the ability to choose our own pivot point, say a point on the stickman, then we just have to worry about positioning the stickman and not the difference between the default pivot point and our desired pivot point.

**Comment by odrick** [comment]
At the moment I don't have much time to develop this project. Feature requests are postponed.
