### ISSUE TITLE
Build for Arch linux

### ISSUE THREAD

**Issue by flamendless** [odrick/free-tex-packer#18]
How to build this to work in arch Linux? 

_Sent from my HUAWEI GR5 2017 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by rtalon83** [comment]
Do you want to make the Electron app for Linux x64, no?

**Comment by flamendless** [comment]
I tend to stay away from any Electron app.

Is the web version of this tool good?

**Comment by odrick** [comment]
Hello. You can build appimage executable, for example:

1 - install node.js
2 - git clone https://github.com/odrick/free-tex-packer.git
3 - cd free-tex-packer
4 - npm install
5 - npm run build-electron
6 - cd electron
7 - change **build - linux - target** to **AppImage** in **package.json**
8 - npm install
9 - npm run build
10 - look at **dist/app** folder ( **FreeTexturePacker-x86_64.AppImage** )
11 - install appimage ( https://itsfoss.com/use-appimage-linux/ )

appimage added to latest release: https://github.com/odrick/free-tex-packer/releases/tag/v0.5.8

**Comment by flamendless** [comment]
Thanks!
