### ISSUE TITLE
Remove unnecessary padding

### ISSUE THREAD

**Issue by kdex** [odrick/free-tex-packer#2]
I've noticed that every texture in the output is currently padded with unnecessary transparent space.

Since the offsets/dimensions of every texture are already stored in another file, is there any chance that this can be removed?

**Comment by odrick** [comment]
Try set **Padding** option to 0

![screenshot-free-tex-packer com-2017-06-01-10-29-15](https://cloud.githubusercontent.com/assets/3988659/26669130/4d2ae9dc-46b5-11e7-9202-d2793d882071.png)

**Comment by ghost** [comment]
​
