### ISSUE TITLE
Does this project support Unity3D?

### ISSUE THREAD

**Issue by iningwei** [odrick/free-tex-packer#21]
or it will support unity3d in the future?

**Comment by odrick** [comment]
Hi. Unity3D does not have unify texture atlas format. However, I can make an exporter for this importer: https://assetstore.unity.com/packages/tools/sprite-management/texturepacker-importer-16641

**Comment by iningwei** [comment]
That would be nice.

**Comment by odrick** [comment]
Done. Please, test it here: http://free-tex-packer.com/test/

**Comment by iningwei** [comment]
Hello,while i clicked Export button,it showed me with"Export error:Unity3D.mst not found".

**Comment by iningwei** [comment]
Ooooops,the error suddenly disappear, succeed output png and tpsheet.
while i put them to unity3d,all works fine with TexturePacker Importer.
Great job!!!

**Comment by odrick** [comment]
Cool :)
