### ISSUE TITLE
Image coordinate offset value is missing

### ISSUE THREAD

**Issue by 942Avril** [odrick/free-tex-packer#24]
Image coordinate offset value is missing

Export the cocos2d project and find that spriteOffset is always {0,0}

**Comment by odrick** [comment]
Fixed. Please, check here: http://free-tex-packer.com/test/

**Comment by 942Avril** [comment]
Can be used, but the result has a floating point value

**Comment by 942Avril** [comment]
The calculated offset value is incorrect

**Comment by odrick** [comment]
Do you have an examples for me? With correct values.

**Comment by 942Avril** [comment]
[example.zip](https://github.com/odrick/free-tex-packer/files/3432234/example.zip)
The texturePacker folder is the result of exporting with texturepacker. The freeTexPacker folder is the result of exporting with the link you sent. The sourceImg folder is the source file.

**Comment by odrick** [comment]
Ok, fixed. Please, try again: http://free-tex-packer.com/test/
Floating point offset values are valid: https://www.codeandweb.com/blog/2016/01/29/cocos2d-plist-format-explained

Calculation offset formula:

**spriteSourceSize.x + spriteSourceSize.width/2 - sourceSize.width/2**

(the offset of the sprite's untrimmed center to the sprite's trimmed center)

For example:

**spriteSourceSize**: x=320, y=55, width=193, height=399
**sourceSize**: width=800, height=800
**offset.x** = 320 + 193/2 - 800/2 = 16.5

FTP pack results:
[pack-result.zip](https://github.com/odrick/free-tex-packer/files/3435039/pack-result.zip)
