### ISSUE TITLE
0.6.0 Extrusion bug

### ISSUE THREAD

**Issue by JoakimCh** [odrick/free-tex-packer#28]
When extruding by x amount of pixels only the pixels at the edge should be repeated this many times. This is not the case, a red box with a blue outline (for example) will mix both blue and red in the extruded pixels (which is a very strange phenomena?).

**Comment by JoakimCh** [comment]
I found a solution though! Adding ```ctx.imageSmoothingEnabled = false``` in ```renderExtrude()``` did the trick! Or add it in ```renderItem()```.

**Comment by odrick** [comment]
Thanks! Fixed.

**Comment by JoakimCh** [comment]
Well, it's broken again... See 4ba6465c51b9d6e6cc524a6d618c0a5c0b0b60ba
