### ISSUE TITLE
the 'realTextureFileName' field of plist

### ISSUE THREAD

**Issue by tonyzzp** [odrick/free-tex-packer#31]
for some software or game engine,the 'realTextureFileName' field of plist should include file extension.
will you add a choice in the export settings?

**Comment by rtalon83** [comment]
What do you mean? One param inside atlas.json?

**Comment by odrick** [comment]
It's part of plist file

<dict>
    <key>format</key>
    <integer>3</integer>
    <key>pixelFormat</key>
    <string><%config.format%></string>
    <key>premultiplyAlpha</key>
    <false/>
    <key>realTextureFileName</key>
    <string><%config.imageFile%></string>
    <key>size</key>
    <string>{<%config.imageWidth%>,<%config.imageHeight%>}</string>
    <key>textureFileName</key>
    <string><%config.imageFile%></string>
</dict>

Looks like config.imageFile does not contains extension. Need to check.

**Comment by tonyzzp** [comment]
> It's part of plist file
> 
> ```
> <dict>
>     <key>format</key>
>     <integer>3</integer>
>     <key>pixelFormat</key>
>     <string><%config.format%></string>
>     <key>premultiplyAlpha</key>
>     <false/>
>     <key>realTextureFileName</key>
>     <string><%config.imageFile%></string>
>     <key>size</key>
>     <string>{<%config.imageWidth%>,<%config.imageHeight%>}</string>
>     <key>textureFileName</key>
>     <string><%config.imageFile%></string>
> </dict>
> ```
> 
> Looks like config.imageFile does not contains extension. Need to check.

yes  i mean that

**Comment by odrick** [comment]
Fixed. Could you test fix here? http://free-tex-packer.com/test/

**Comment by tonyzzp** [comment]
> Fixed. Could you test fix here? http://free-tex-packer.com/test/

yes,it is ok now for me.
but I found that the 'realTextureFileName' and 'textureFileName' is the same in 'TexturePacker'

**Comment by odrick** [comment]
Good. I'm not sure about right 'realTextureFileName' and 'textureFileName' values. And cocos2d does not have normal documentation...
