### ISSUE TITLE
Trim is checked when the editor starts with a custom exporter that doesn't allow trimming

### ISSUE THREAD

**Issue by MightyPrinny** [odrick/free-tex-packer#33]
The exporter doesn't allow trimming, but trim is checked when the program starts (I hit submit on accident, sorry if the unedited message was weird).

**Comment by odrick** [comment]
Fixed. Could you test fix here http://free-tex-packer.com/test/ ?

**Comment by MightyPrinny** [comment]
It works

**Comment by odrick** [comment]
Cool :) Will be released soon. Web version updated.
