### ISSUE TITLE
Paths in .ftpp files

### ISSUE THREAD

**Issue by zyndor** [odrick/free-tex-packer#35]
Hi Odrick,

Thanks for the awesome tool that FreeTexPacker is.

One issue I've found with it is that the .ftpp files store _absolute_ paths (for `savePath` and `folders`), which is rather limiting when trying to check them into a repository that's being worked on from multiple workstations / by multiple users.

A more robust solution would be to save these paths _relative_ to the location of the *.ftpp.

I have tried to manually edit the .ftpp to this end, but unfortunately that seems to be a no go - the image from these 'relative' folders don't show and export hangs the app (on Ubuntu 16.04 at least).
 
Would you please consider adding support for saving the export paths _relative_ to the location of the .ftpp? (I'd attempt this myself if I wasn't limited by lack of knowledge of Electron and building FreeTexPacker.)

Thank you for your time.

**Comment by odrick** [comment]
Hey.

We need to think about how to make relative paths support and don't break projects with absolute paths...

**Comment by zyndor** [comment]
Sorry about the delayed reply. I'd treat any path that doesn't start with "^([A-Z]\:|/)" as relative -- pre-existing paths presumably won't match (and will keep working). However I haven't had a chance to look at the code base, and the devil is in the details.

I'm quite busy these days but I'll see if I can put together a PR that works, in my spare time.

**Comment by blinkuz** [comment]
Anything new regarding this ?, I'm having problems sharing projects with my friends since the images don't load when I move them to another computer.

**Comment by dacanizares** [comment]
Anything new?

**Comment by odrick** [comment]
At the moment I don't have much time to develop this project. Feature requests are postponed.
