### ISSUE TITLE
Adding custom exporters

### ISSUE THREAD

**Issue by MarcoLizza** [odrick/free-tex-packer#39]
Hi. From my understanding, at the moment the application supports custom exporters but this requires to copy-and-paste the exporter code into the exporter-edit dialog. Shouldn't be easier/more-convenient to have a "exporters" folder in the application installation path (or elsewhere in the user-profile folder) where MST file can be put in order to have them ready in the application?

**Comment by odrick** [comment]
Yes, that's right. If you need a permanent exporter, just send it to me and I will add it to build.
