### ISSUE TITLE
Instructions how to install on laptop

### ISSUE THREAD

**Issue by wyattbiker** [odrick/free-tex-packer#4]
This is an excellent utility. Whats the best way to install and run this on my laptop.

I am on a Mac but if you have Windows instructions only that will do as well.

Thanks!

**Comment by odrick** [comment]
Hi!

This is online, not desktop, tool :) However, you can run it locally:

- clone repo, or download and unpack zip ( https://github.com/odrick/free-tex-packer/archive/master.zip )
- install node.js: https://nodejs.org/en/
- execute in project folder from console "npm install"
- execute "npm start"
- open in browser http://localhost:4000/ 

For local use, I recommend this: https://github.com/odrick/gulp-free-tex-packer

**Comment by odrick** [comment]
Desktop versions for win, mac and linux released: https://github.com/odrick/free-tex-packer/releases
