### ISSUE TITLE
can't build electron package

### ISSUE THREAD

**Issue by morder** [odrick/free-tex-packer#40]
`npm run build-electron`
I got this error
```
WARNING in ./node_modules/chokidar/lib/fsevents-handler.js
Module not found: Error: Can't resolve 'fsevents' in '/home/yanis/projects/free-tex-packer/node_modules/chokidar/lib'
 @ ./node_modules/chokidar/lib/fsevents-handler.js
 @ ./node_modules/chokidar/index.js
 @ ./src/client/platform/electron/FileSystem.js
 @ ./src/client/ui/ImagesList.jsx
 @ ./src/client/platform/electron/Controller.js
 @ ./src/client/index.js
 @ multi babel-polyfill ./src/client/index
```

My system is linux and `fsevents` didn't work on this system but `chokidar` requires it

**Comment by rtalon83** [comment]
I'm testing electron project and yes, there is a WARNING about fsevents but I can make the app.
1. build-electron (warning jsevents ignored)
2. free-tex-packer/electron/package.json (npm install)
3. free-tex-packer/electron/package.json ( npm start )

https://github.com/webpack/webpack/issues/8364

**Comment by morder** [comment]
@rtalon83 what is your system?

**Comment by rtalon83** [comment]
Windows 10. 64

**Comment by rtalon83** [comment]
Ok, your problem is in Linux.

**Comment by piratesephiroth** [comment]
so we can only build the project on MacOS...

**Comment by morder** [comment]
@piratesephiroth you can create virtual machine with any Linux distro and test building

**Comment by piratesephiroth** [comment]
> 
> 
> @piratesephiroth you can create virtual machine with any Linux distro and test building

well, it actually builds just fine on Windows.

**Comment by odrick** [comment]
Build fine on native Win. Linux and Mac on Virtual Box.
