### ISSUE TITLE
Optimal packer always allows rotation

### ISSUE THREAD

**Issue by MightyPrinny** [odrick/free-tex-packer#41]
In version 0.6.5 the optimal packer always allows rotation, luckily for me the MaxRectsPacker in Smart mode seems to do the same thing as the optimal packer but it respects my rotation settings.

**Comment by rtalon83** [comment]
OptimalPacker studies the best and optimal pack configuration, then it cans choose o not the rotation feature.
I did a PR to improve the UI. #42

**Comment by odrick** [comment]
Some engines cannot render atlases with rotation. Therefore, I think this is a bug. Fixed.
