### ISSUE TITLE
PNG compression

### ISSUE THREAD

**Issue by My-Key** [odrick/free-tex-packer#44]
Hi,

I'm trying to make atlas with textures that are SDF (signed distance field) and output image have to be uncompressed to render properly.

After export you can see a difference between output (left) and source (right) especially visible on the edges. (Alpha channel is disabled to make difference visible, on the output alpha was the same as on the source)
![obraz](https://user-images.githubusercontent.com/6819647/82497068-f8c7ed00-9aed-11ea-905b-995c0e103983.png)

Is there an option to change PNG compression? I tried to look for it in sources, but couldn't find it.

**Comment by dranitski** [comment]
i can not see any difference on image provided

**Comment by odrick** [comment]
No, this is impossible. PNG compressed by webkit and have no options.
