### ISSUE TITLE
Invalid size.

### ISSUE THREAD

**Issue by atillabyte** [odrick/free-tex-packer#51]
I can't import this image for some reason. I was unable to load it into SFML, presumably because the texture size was too large, so I thought I'd pack it to make my graphics card handle it - but I can't, maybe for the same reason?

![screenshot](https://i.imgur.com/A7xzvtQ.png)

The image I'm trying to import:
https://user-images.githubusercontent.com/2405874/86038545-1b172980-ba0f-11ea-852f-e4a8389a1cfe.png

**Comment by odrick** [comment]
You cat try to set Width texture to 14368
