### ISSUE TITLE
Strange sorting

### ISSUE THREAD

**Issue by Cr0c81** [odrick/free-tex-packer#52]
How sort in output (JSON array)? I have 6 files atlas and need sort by name (because use animation), but elements placed in random atlas.
![image](https://user-images.githubusercontent.com/25858329/90403223-50ec9c00-e0a9-11ea-8cb2-82c1dc0a17dc.png)

**Comment by Cr0c81** [comment]
Please let me know the approximate completion date for the current issues

сб, 22 авг. 2020 г. в 15:39, nonunknown <notifications@github.com>:

**Comment by odrick** [comment]
This is not the responsibility of the texture packer. The purpose of the texture packer is to create the most optimal atlases. Generating animation is the task of an application that uses atlases. By design.

**Comment by lmf-git** [comment]
What the fuck.

**Comment by lmf-git** [comment]
How is it not the responsibility of this tool to output in a reasonable way compared to input?

What a stupid cop out and a complete deal breaker for actually using this thing.

Why would you just completely write off all of the great work that has been done on this tool by dropping the ball on the last .5%? Absolutely insane.
