### ISSUE TITLE
Program freezes when importing files or folder with "[ ]" in their names

### ISSUE THREAD

**Issue by ww9** [odrick/free-tex-packer#54]
Program freezes when importing files or folder with "[ ]" in their names.

Steps to reproduce on Windows:

- Create a directory or file containing [1] and try to import it

![image](https://user-images.githubusercontent.com/27555162/93021239-ac7a4e80-f5af-11ea-91d0-87879fc6f6dd.png)

**Comment by odrick** [comment]
Related to https://github.com/here-be/snapdragon/issues/11
In this case files and folders will be excluded from watching.
Will be released at 0.6.7
