### ISSUE TITLE
Allow channel masking for input images and re-use pixels for independent images

### ISSUE THREAD

**Issue by JannikGM** [odrick/free-tex-packer#58]
We do have a mix of R (SDF), RG (2-component-SDF), RGB (opaque) and RGBA images (transparent) texture sources.

It would be nice if free-tex-packer could pack each color channel independently, thereby potentially overlapping up to 4 separate grayscale images. Say grayscale_image1.png would end up in R channel at (0,0); grayscale_image2.png would end up in G channel at (0,0), etc.

I know that this would significantly complicate the algorithms in free-tex-packer, so it might be out of scope.
I still hope that it is considered for future revisions, future projects, or that someone in the comments can recommend tooling which can already do this.

*(Specifically, I need this in the CLI version, but I assume this issue tracker goes for both)*

**Comment by odrick** [comment]
This is a very rare feature. I can suggest you to fork the project and implement the required functionality.
