### ISSUE TITLE
Windows command line tool

### ISSUE THREAD

**Issue by Kigs-framework** [odrick/free-tex-packer#59]
Hello,

    Do you think that it would be possible to build a command line tool for Windows based on free-tex-packer. Not taking a ftpp project file as input, but directly all the arguments like : --textureName "my-texture" --fixedSize true ...

    I don't know if electron enable this ?

    thanks

**Comment by odrick** [comment]
Hi. Right now ftp have a lot of CLI tools. Look at:

https://github.com/odrick/free-tex-packer-cli
https://github.com/odrick/gulp-free-tex-packer
