### ISSUE TITLE
Can't paste tinypng key

### ISSUE THREAD

**Issue by naveed-ahmad** [odrick/free-tex-packer#6]
We can't paste the key of tinypng in mac version.

TinyPng key is huge, manually typing the key isn't that easy.

**Comment by odrick** [comment]
Does insertion through the context menu not work, or using hot keys?

**Comment by odrick** [comment]
Context menu for input field added. Please, check v0.5.1: https://github.com/odrick/free-tex-packer/releases/tag/v0.5.1

**Comment by naveed-ahmad** [comment]
Yep, context menu works now. Thanks for quick update.
