### ISSUE TITLE
Command line ?

### ISSUE THREAD

**Issue by naveed-ahmad** [odrick/free-tex-packer#7]
This is really cool tool, adding command line will make it even better.

**Comment by odrick** [comment]
Hello. CLI exists: https://github.com/odrick/free-tex-packer-cli
There are also modules for gulp https://github.com/odrick/gulp-free-tex-packer and webpack https://github.com/odrick/webpack-free-tex-packer

**Comment by naveed-ahmad** [comment]
thank you 😍
