### ISSUE TITLE
Frames order by number is incorrect.

### ISSUE THREAD

**Issue by 3GOMESz** [odrick/free-tex-packer#9]
When you drag and drop the files ended with some number on FTP, they are organized in a wrong order.

Files: 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25
Result: 1, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 2, 20, 21, 22, 23, 24, 25, 3, 4, 5, 6, 7, 8, 9

Example: https://i.imgur.com/jpOiHce.png

**Comment by odrick** [comment]
File names sorted as strings (not a numbers). The same sorting method is used, for example, in Total Commander, Krusader, etc. You can add leading "0" to the file names for the desired result.

**Comment by 3GOMESz** [comment]
I see. So the only way is keeping the filenames like this?

- 001
- 002
- 003
- 004
- 005
- 006
- 007
- 008
- 009
- 010
- 011
- 012

**Comment by odrick** [comment]
Please, check test version here http://free-tex-packer.com/test/ . Experimental sorting method implemented.

**Comment by 3GOMESz** [comment]
All working! 👍 
This can speed up the work of those who are too lazy to rename files hahahahaha.

**Comment by odrick** [comment]
Ok) This sorting method will be include to the next release.

**Comment by dimmduh** [comment]
omg...sorting odes not work. I even can not drag order in files list. It's basic and it's not implemented. Thx for work, but not usable for me.
